`ifndef NETWORK_CONFIG_VH
`define NETWORK_CONFIG_VH

`define IPT_BIT                      16
`define WGT_BIT                      16
`define OPT_BIT                      16
`define PSUM_BIT                     48

`define CONV_LAYER_NUM               6

`define L0_CONV_IDX                  0
`define L0_IPT_SIDE                  32
`define L0_OPT_SIDE                  16
`define L0_OPT_AREA                  256
`define L0_TILE_IPT_SIDE             8
`define L0_TILE_IPT_AREA             64
`define L0_TILE_OPT_SIDE             4
`define L0_TILE_OPT_AREA             16
`define L0_TILE_NUM                  16
`define L0_TILE_NUM_X                4
`define L0_TILE_NUM_Y                4
`define L0_CHANNEL                   1
`define L0_FILTER                    8
`define L0_KERNEL                    3
`define L0_KERNEL_STRIDE             2
`define L0_PAD                       1
`define L0_RELU                      1
`define L0_WGT_DEPTH                 72
`define L0_BIAS_DEPTH                8
`define L0_CHANNEL_GROUP_NUM         1
`define L0_FILTER_GROUP_NUM          4
`define L0_BL_REQ_LEN                2
`define L0_BR_READ_LEN               1
`define L0_WL_REQ_LEN                18
`define L0_WR_READ_LEN               9
`define L0_TR_READ_LEN               100
`define L0_BL_BANK_DEPTH             1
`define L0_WL_BANK_DEPTH             9
`define L0_BL_STRIDE                 2
`define L0_BR_STRIDE                 1
`define L0_WL_FILT_GRP_STRIDE        18
`define L0_WR_CH_GRP_STRIDE          9
`define L0_TL_ROW_STRIDE             256
`define L0_TL_COL_STRIDE             8
`define L0_TL_CH_GRP_STRIDE          1024
`define L0_TS_ROW_STRIDE             64
`define L0_TS_COL_STRIDE             4
`define L0_TS_CH_GRP_STRIDE          256
`define L0_OBUF_TILE_ROW_STRIDE      64
`define L0_OBUF_TILE_CH_STRIDE       256
`define L0_PSC_SUM_NUM               1

`define L1_CONV_IDX                  1
`define L1_IPT_SIDE                  16
`define L1_OPT_SIDE                  8
`define L1_OPT_AREA                  64
`define L1_TILE_IPT_SIDE             8
`define L1_TILE_IPT_AREA             64
`define L1_TILE_OPT_SIDE             4
`define L1_TILE_OPT_AREA             16
`define L1_TILE_NUM                  4
`define L1_TILE_NUM_X                2
`define L1_TILE_NUM_Y                2
`define L1_CHANNEL                   8
`define L1_FILTER                    4
`define L1_KERNEL                    3
`define L1_KERNEL_STRIDE             2
`define L1_PAD                       1
`define L1_RELU                      1
`define L1_WGT_DEPTH                 288
`define L1_BIAS_DEPTH                4
`define L1_CHANNEL_GROUP_NUM         4
`define L1_FILTER_GROUP_NUM          2
`define L1_BL_REQ_LEN                2
`define L1_BR_READ_LEN               1
`define L1_WL_REQ_LEN                144
`define L1_WR_READ_LEN               18
`define L1_TR_READ_LEN               100
`define L1_BL_BANK_DEPTH             1
`define L1_WL_BANK_DEPTH             72
`define L1_BL_STRIDE                 2
`define L1_BR_STRIDE                 1
`define L1_WL_FILT_GRP_STRIDE        144
`define L1_WR_CH_GRP_STRIDE          18
`define L1_TL_ROW_STRIDE             128
`define L1_TL_COL_STRIDE             8
`define L1_TL_CH_GRP_STRIDE          256
`define L1_TS_ROW_STRIDE             32
`define L1_TS_COL_STRIDE             4
`define L1_TS_CH_GRP_STRIDE          64
`define L1_OBUF_TILE_ROW_STRIDE      32
`define L1_OBUF_TILE_CH_STRIDE       64
`define L1_PSC_SUM_NUM               4

`define L2_CONV_IDX                  2
`define L2_IPT_SIDE                  8
`define L2_OPT_SIDE                  8
`define L2_OPT_AREA                  64
`define L2_TILE_IPT_SIDE             8
`define L2_TILE_IPT_AREA             64
`define L2_TILE_OPT_SIDE             8
`define L2_TILE_OPT_AREA             64
`define L2_TILE_NUM                  1
`define L2_TILE_NUM_X                1
`define L2_TILE_NUM_Y                1
`define L2_CHANNEL                   4
`define L2_FILTER                    4
`define L2_KERNEL                    3
`define L2_KERNEL_STRIDE             1
`define L2_PAD                       1
`define L2_RELU                      1
`define L2_WGT_DEPTH                 144
`define L2_BIAS_DEPTH                4
`define L2_CHANNEL_GROUP_NUM         2
`define L2_FILTER_GROUP_NUM          2
`define L2_BL_REQ_LEN                2
`define L2_BR_READ_LEN               1
`define L2_WL_REQ_LEN                72
`define L2_WR_READ_LEN               18
`define L2_TR_READ_LEN               100
`define L2_BL_BANK_DEPTH             1
`define L2_WL_BANK_DEPTH             36
`define L2_BL_STRIDE                 2
`define L2_BR_STRIDE                 1
`define L2_WL_FILT_GRP_STRIDE        72
`define L2_WR_CH_GRP_STRIDE          18
`define L2_TL_ROW_STRIDE             64
`define L2_TL_COL_STRIDE             8
`define L2_TL_CH_GRP_STRIDE          64
`define L2_TS_ROW_STRIDE             64
`define L2_TS_COL_STRIDE             8
`define L2_TS_CH_GRP_STRIDE          64
`define L2_OBUF_TILE_ROW_STRIDE      64
`define L2_OBUF_TILE_CH_STRIDE       64
`define L2_PSC_SUM_NUM               2


`define L3_CONV_IDX                  3
`define L3_IPT_SIDE                  8
`define L3_OPT_SIDE                  8
`define L3_OPT_AREA                  64
`define L3_TILE_IPT_SIDE             8
`define L3_TILE_IPT_AREA             64
`define L3_TILE_OPT_SIDE             8
`define L3_TILE_OPT_AREA             64
`define L3_TILE_NUM                  1
`define L3_TILE_NUM_X                1
`define L3_TILE_NUM_Y                1
`define L3_CHANNEL                   2
`define L3_FILTER                    4
`define L3_KERNEL                    3
`define L3_KERNEL_STRIDE             1
`define L3_PAD                       1
`define L3_RELU                      1
`define L3_WGT_DEPTH                 72
`define L3_BIAS_DEPTH                4
`define L3_CHANNEL_GROUP_NUM         1
`define L3_FILTER_GROUP_NUM          2
`define L3_BL_REQ_LEN                2
`define L3_BR_READ_LEN               1
`define L3_WL_REQ_LEN                36
`define L3_WR_READ_LEN               18
`define L3_TR_READ_LEN               100
`define L3_BL_BANK_DEPTH             1
`define L3_WL_BANK_DEPTH             18
`define L3_BL_STRIDE                 2
`define L3_BR_STRIDE                 1
`define L3_WL_FILT_GRP_STRIDE        36
`define L3_WR_CH_GRP_STRIDE          18
`define L3_TL_ROW_STRIDE             64
`define L3_TL_COL_STRIDE             8
`define L3_TL_CH_GRP_STRIDE          64
`define L3_TS_ROW_STRIDE             64
`define L3_TS_COL_STRIDE             8
`define L3_TS_CH_GRP_STRIDE          64
`define L3_OBUF_TILE_ROW_STRIDE      64
`define L3_OBUF_TILE_CH_STRIDE       64
`define L3_PSC_SUM_NUM               1

`define L4_CONV_IDX                  4
`define L4_IPT_SIDE                  8
`define L4_OPT_SIDE                  8
`define L4_OPT_AREA                  64
`define L4_TILE_IPT_SIDE             8
`define L4_TILE_IPT_AREA             64
`define L4_TILE_OPT_SIDE             8
`define L4_TILE_OPT_AREA             64
`define L4_TILE_NUM                  1
`define L4_TILE_NUM_X                1
`define L4_TILE_NUM_Y                1
`define L4_CHANNEL                   4
`define L4_FILTER                    8
`define L4_KERNEL                    3
`define L4_KERNEL_STRIDE             1
`define L4_PAD                       1
`define L4_RELU                      1
`define L4_WGT_DEPTH                 288
`define L4_BIAS_DEPTH                8
`define L4_CHANNEL_GROUP_NUM         2
`define L4_FILTER_GROUP_NUM          4
`define L4_BL_REQ_LEN                2
`define L4_BR_READ_LEN               1
`define L4_WL_REQ_LEN                72
`define L4_WR_READ_LEN               18
`define L4_TR_READ_LEN               100
`define L4_BL_BANK_DEPTH             1
`define L4_WL_BANK_DEPTH             36
`define L4_BL_STRIDE                 2
`define L4_BR_STRIDE                 1
`define L4_WL_FILT_GRP_STRIDE        72
`define L4_WR_CH_GRP_STRIDE          18
`define L4_TL_ROW_STRIDE             64
`define L4_TL_COL_STRIDE             8
`define L4_TL_CH_GRP_STRIDE          64
`define L4_TS_ROW_STRIDE             64
`define L4_TS_COL_STRIDE             8
`define L4_TS_CH_GRP_STRIDE          64
`define L4_OBUF_TILE_ROW_STRIDE      64
`define L4_OBUF_TILE_CH_STRIDE       64
`define L4_PSC_SUM_NUM               2


`define L5_CONV_IDX                  5
`define L5_IPT_SIDE                  8
`define L5_OPT_SIDE                  8
`define L5_OPT_AREA                  64
`define L5_TILE_IPT_SIDE             8
`define L5_TILE_IPT_AREA             64
`define L5_TILE_OPT_SIDE             8
`define L5_TILE_OPT_AREA             64
`define L5_TILE_NUM                  1
`define L5_TILE_NUM_X                1
`define L5_TILE_NUM_Y                1
`define L5_CHANNEL                   12
`define L5_FILTER                    1
`define L5_KERNEL                    3
`define L5_KERNEL_STRIDE             1
`define L5_PAD                       1
`define L5_RELU                      0
`define L5_WGT_DEPTH                 108
`define L5_BIAS_DEPTH                1
`define L5_CHANNEL_GROUP_NUM         6
`define L5_FILTER_GROUP_NUM          1
`define L5_BL_REQ_LEN                1
`define L5_BR_READ_LEN               1
`define L5_WL_REQ_LEN                108
`define L5_WR_READ_LEN               18
`define L5_TR_READ_LEN               100
`define L5_BL_BANK_DEPTH             1
`define L5_WL_BANK_DEPTH             108
`define L5_BL_STRIDE                 1
`define L5_BR_STRIDE                 1
`define L5_WL_FILT_GRP_STRIDE        108
`define L5_WR_CH_GRP_STRIDE          18
`define L5_TL_ROW_STRIDE             64
`define L5_TL_COL_STRIDE             8
`define L5_TL_CH_GRP_STRIDE          64
`define L5_TS_ROW_STRIDE             64
`define L5_TS_COL_STRIDE             8
`define L5_TS_CH_GRP_STRIDE          64
`define L5_OBUF_TILE_ROW_STRIDE      64
`define L5_OBUF_TILE_CH_STRIDE       64
`define L5_PSC_SUM_NUM               6

`define MAX_BIAS_DEPTH               8
`define MAX_WGT_DEPTH                288
`define MAX_FILTER                   8
`define MAX_GROUP_FILTER             2
`define MAX_FILTER_GROUP_NUM         4
`define MAX_TILE_SIDE                8
`define MAX_TILE_AREA                64
`define MAX_TILE_NUM                 16
`define MAX_CHANNEL                  12
`define MAX_GROUP_CHANNEL            2
`define MAX_CHANNEL_GROUP_NUM        6
`define MAX_IPT_SIDE                 32
`define MAX_IPT_AREA                 1024
`define MAX_OPT_SIDE                 32
`define MAX_OPT_AREA                 1024
`define MAX_PAD_TILE_SIDE            10
`define MAX_PAD_TILE_AREA            100

`endif